In [1]:
import numpy as np

### Arithmatic Operations

In [2]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

In [4]:
result_sum = a1 + a2
result_sum

array([ 7,  9, 11, 13, 15])

In [5]:
result_remainder = a2 // a1
result_remainder

array([6, 3, 2, 2, 2])

### Broadcasting

In [6]:
l = [10,20,30,40,50,60]
arr_l = np.array(l)

In [8]:
arr_l + 5

array([15, 25, 35, 45, 55, 65])

### Deep and Shallow Copy

In [12]:
arr_ds = np.arange(1,26).reshape(5,5)
arr_ds

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
arr_ds + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [14]:
arr_ds

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr = np.arange(1,11)

In [16]:
arr_slice = arr[: 5]
arr_slice = arr_slice * 10
arr_slice

array([10, 20, 30, 40, 50])

In [17]:
arr # this is shallow copy where changes made in slice of array does not affect the main array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
brr = arr
brr[0] = 999

In [19]:
brr

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [20]:
arr # this is deep copy where changes made are reflected in main array as well because both point to same memory location

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [21]:
brr_copy = arr.copy()
brr_copy[0] = 111

In [22]:
brr_copy

array([111,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [23]:
arr

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

### Matrix Operations

In [25]:
A = np.array([[1,2],
            [3,4]])
B = np.array([[5,6],
            [7,8]])

In [26]:
A @ B

array([[19, 22],
       [43, 50]])

In [27]:
A.T

array([[1, 3],
       [2, 4]])

### Stacking Array

In [28]:
a = np.arange(1,6)
b = np.arange(6,11)

In [30]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])